using SweetCakeShop.Models.AI;

namespace SweetCakeShop.Services.AI.Customer
{
    /// <summary>
    /// Keeps the product records returned by safe, read-only AI tools so the UI can render
    /// product cards without trusting product data generated by the model.
    /// </summary>
    public interface ICustomerToolCallContext
    {
        IReadOnlyList<ProductFactDto> Products { get; }
        void RecordProducts(IEnumerable<ProductFactDto> products);
        void Clear();
    }

    public sealed class CustomerToolCallContext : ICustomerToolCallContext
    {
        private readonly List<ProductFactDto> _products = [];

        public IReadOnlyList<ProductFactDto> Products => _products;

        public void RecordProducts(IEnumerable<ProductFactDto> products)
        {
            foreach (var product in products)
            {
                var alreadyRecorded = _products.Any(existing =>
                    (product.ProductId > 0 && existing.ProductId == product.ProductId)
                    || string.Equals(existing.Name, product.Name, StringComparison.OrdinalIgnoreCase));

                if (!alreadyRecorded)
                    _products.Add(product);
            }
        }

        public void Clear() => _products.Clear();
    }
}
